// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Problem struct {
	ID            string
	Slug          string
	Title         string
	Difficulty    string
	Statement     string
	Constraints   string
	TimeLimitMs   int32
	MemoryLimitMb int32
	MaxScore      int32
	Published     bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ProblemSample struct {
	ID          string
	ProblemID   string
	Ordinal     int32
	Input       string
	Output      string
	Explanation string
}

type ProblemScore struct {
	UserID           string
	ProblemID        string
	BestScore        int32
	BestSubmissionID pgtype.UUID
	UpdatedAt        time.Time
}

type ProblemTest struct {
	ID          string
	ProblemID   string
	Ordinal     int32
	Input       []byte
	Expected    []byte
	InputSha    string
	ExpectedSha string
	Points      int32
}

type Session struct {
	Token     string
	UserID    string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Submission struct {
	ID           string
	UserID       string
	ProblemID    string
	Language     string
	Code         string
	State        string
	Verdict      pgtype.Text
	Score        int32
	MaxScore     int32
	TestsTotal   int32
	TestsDone    int32
	CompileError pgtype.Text
	MaxTimeMs    int32
	MaxMemoryKb  int32
	CreatedAt    time.Time
	ClaimedAt    *time.Time
	ClaimedBy    pgtype.Text
	LeaseUntil   *time.Time
	Attempts     int32
	FinishedAt   *time.Time
}

type SubmissionTest struct {
	SubmissionID string
	Ordinal      int32
	Verdict      string
	TimeMs       int32
	MemoryKb     int32
	Points       int32
}

type User struct {
	ID           string
	Username     string
	DisplayName  string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
	LastLoginAt  *time.Time
}
