// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: problems.sql

package sqlc

import (
	"context"
)

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems (slug, title, difficulty, statement, constraints, time_limit_ms, memory_limit_mb, max_score, published)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, slug, title, difficulty, statement, constraints, time_limit_ms, memory_limit_mb, max_score, published, created_at, updated_at
`

type CreateProblemParams struct {
	Slug          string
	Title         string
	Difficulty    string
	Statement     string
	Constraints   string
	TimeLimitMs   int32
	MemoryLimitMb int32
	MaxScore      int32
	Published     bool
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, createProblem,
		arg.Slug,
		arg.Title,
		arg.Difficulty,
		arg.Statement,
		arg.Constraints,
		arg.TimeLimitMs,
		arg.MemoryLimitMb,
		arg.MaxScore,
		arg.Published,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Difficulty,
		&i.Statement,
		&i.Constraints,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.MaxScore,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSample = `-- name: CreateSample :one
INSERT INTO problem_samples (problem_id, ordinal, input, output, explanation)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, problem_id, ordinal, input, output, explanation
`

type CreateSampleParams struct {
	ProblemID   string
	Ordinal     int32
	Input       string
	Output      string
	Explanation string
}

func (q *Queries) CreateSample(ctx context.Context, arg CreateSampleParams) (ProblemSample, error) {
	row := q.db.QueryRow(ctx, createSample,
		arg.ProblemID,
		arg.Ordinal,
		arg.Input,
		arg.Output,
		arg.Explanation,
	)
	var i ProblemSample
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Ordinal,
		&i.Input,
		&i.Output,
		&i.Explanation,
	)
	return i, err
}

const createTest = `-- name: CreateTest :one
INSERT INTO problem_tests (problem_id, ordinal, input, expected, input_sha, expected_sha, points)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, problem_id, ordinal, input, expected, input_sha, expected_sha, points
`

type CreateTestParams struct {
	ProblemID   string
	Ordinal     int32
	Input       []byte
	Expected    []byte
	InputSha    string
	ExpectedSha string
	Points      int32
}

func (q *Queries) CreateTest(ctx context.Context, arg CreateTestParams) (ProblemTest, error) {
	row := q.db.QueryRow(ctx, createTest,
		arg.ProblemID,
		arg.Ordinal,
		arg.Input,
		arg.Expected,
		arg.InputSha,
		arg.ExpectedSha,
		arg.Points,
	)
	var i ProblemTest
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Ordinal,
		&i.Input,
		&i.Expected,
		&i.InputSha,
		&i.ExpectedSha,
		&i.Points,
	)
	return i, err
}

const deleteProblem = `-- name: DeleteProblem :execrows
DELETE FROM problems WHERE id = $1
`

func (q *Queries) DeleteProblem(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProblem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSamplesForProblem = `-- name: DeleteSamplesForProblem :exec
DELETE FROM problem_samples WHERE problem_id = $1
`

func (q *Queries) DeleteSamplesForProblem(ctx context.Context, problemID string) error {
	_, err := q.db.Exec(ctx, deleteSamplesForProblem, problemID)
	return err
}

const deleteTestsForProblem = `-- name: DeleteTestsForProblem :exec
DELETE FROM problem_tests WHERE problem_id = $1
`

func (q *Queries) DeleteTestsForProblem(ctx context.Context, problemID string) error {
	_, err := q.db.Exec(ctx, deleteTestsForProblem, problemID)
	return err
}

const getFullTestsForProblem = `-- name: GetFullTestsForProblem :many
SELECT id, problem_id, ordinal, input, expected, input_sha, expected_sha, points FROM problem_tests WHERE problem_id = $1 ORDER BY ordinal
`

func (q *Queries) GetFullTestsForProblem(ctx context.Context, problemID string) ([]ProblemTest, error) {
	rows, err := q.db.Query(ctx, getFullTestsForProblem, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProblemTest{}
	for rows.Next() {
		var i ProblemTest
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Ordinal,
			&i.Input,
			&i.Expected,
			&i.InputSha,
			&i.ExpectedSha,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProblemByID = `-- name: GetProblemByID :one
SELECT id, slug, title, difficulty, statement, constraints, time_limit_ms, memory_limit_mb, max_score, published, created_at, updated_at FROM problems WHERE id = $1
`

func (q *Queries) GetProblemByID(ctx context.Context, id string) (Problem, error) {
	row := q.db.QueryRow(ctx, getProblemByID, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Difficulty,
		&i.Statement,
		&i.Constraints,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.MaxScore,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProblemBySlug = `-- name: GetProblemBySlug :one
SELECT id, slug, title, difficulty, statement, constraints, time_limit_ms, memory_limit_mb, max_score, published, created_at, updated_at FROM problems WHERE slug = $1
`

func (q *Queries) GetProblemBySlug(ctx context.Context, slug string) (Problem, error) {
	row := q.db.QueryRow(ctx, getProblemBySlug, slug)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Difficulty,
		&i.Statement,
		&i.Constraints,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.MaxScore,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedProblemBySlug = `-- name: GetPublishedProblemBySlug :one
SELECT id, slug, title, difficulty, statement, constraints, time_limit_ms, memory_limit_mb, max_score, published, created_at, updated_at FROM problems WHERE slug = $1 AND published = true
`

func (q *Queries) GetPublishedProblemBySlug(ctx context.Context, slug string) (Problem, error) {
	row := q.db.QueryRow(ctx, getPublishedProblemBySlug, slug)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Difficulty,
		&i.Statement,
		&i.Constraints,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.MaxScore,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSamplesForProblem = `-- name: GetSamplesForProblem :many
SELECT id, problem_id, ordinal, input, output, explanation FROM problem_samples WHERE problem_id = $1 ORDER BY ordinal
`

func (q *Queries) GetSamplesForProblem(ctx context.Context, problemID string) ([]ProblemSample, error) {
	rows, err := q.db.Query(ctx, getSamplesForProblem, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProblemSample{}
	for rows.Next() {
		var i ProblemSample
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Ordinal,
			&i.Input,
			&i.Output,
			&i.Explanation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestsForProblem = `-- name: GetTestsForProblem :many
SELECT id, problem_id, ordinal, input_sha, expected_sha, points FROM problem_tests WHERE problem_id = $1 ORDER BY ordinal
`

type GetTestsForProblemRow struct {
	ID          string
	ProblemID   string
	Ordinal     int32
	InputSha    string
	ExpectedSha string
	Points      int32
}

func (q *Queries) GetTestsForProblem(ctx context.Context, problemID string) ([]GetTestsForProblemRow, error) {
	rows, err := q.db.Query(ctx, getTestsForProblem, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTestsForProblemRow{}
	for rows.Next() {
		var i GetTestsForProblemRow
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Ordinal,
			&i.InputSha,
			&i.ExpectedSha,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProblems = `-- name: ListAllProblems :many
SELECT id, slug, title, difficulty, statement, constraints, time_limit_ms, memory_limit_mb, max_score, published, created_at, updated_at FROM problems ORDER BY created_at DESC
`

func (q *Queries) ListAllProblems(ctx context.Context) ([]Problem, error) {
	rows, err := q.db.Query(ctx, listAllProblems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Problem{}
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Difficulty,
			&i.Statement,
			&i.Constraints,
			&i.TimeLimitMs,
			&i.MemoryLimitMb,
			&i.MaxScore,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedProblems = `-- name: ListPublishedProblems :many
SELECT id, slug, title, difficulty, statement, constraints, time_limit_ms, memory_limit_mb, max_score, published, created_at, updated_at FROM problems WHERE published = true ORDER BY created_at DESC
`

func (q *Queries) ListPublishedProblems(ctx context.Context) ([]Problem, error) {
	rows, err := q.db.Query(ctx, listPublishedProblems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Problem{}
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Difficulty,
			&i.Statement,
			&i.Constraints,
			&i.TimeLimitMs,
			&i.MemoryLimitMb,
			&i.MaxScore,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProblemPublished = `-- name: SetProblemPublished :execrows
UPDATE problems SET published = $2, updated_at = now() WHERE id = $1
`

type SetProblemPublishedParams struct {
	ID        string
	Published bool
}

func (q *Queries) SetProblemPublished(ctx context.Context, arg SetProblemPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProblemPublished, arg.ID, arg.Published)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProblem = `-- name: UpdateProblem :one
UPDATE problems
SET title = $2, difficulty = $3, statement = $4, constraints = $5, time_limit_ms = $6, memory_limit_mb = $7, max_score = $8, published = $9, updated_at = now()
WHERE id = $1
RETURNING id, slug, title, difficulty, statement, constraints, time_limit_ms, memory_limit_mb, max_score, published, created_at, updated_at
`

type UpdateProblemParams struct {
	ID            string
	Title         string
	Difficulty    string
	Statement     string
	Constraints   string
	TimeLimitMs   int32
	MemoryLimitMb int32
	MaxScore      int32
	Published     bool
}

func (q *Queries) UpdateProblem(ctx context.Context, arg UpdateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, updateProblem,
		arg.ID,
		arg.Title,
		arg.Difficulty,
		arg.Statement,
		arg.Constraints,
		arg.TimeLimitMs,
		arg.MemoryLimitMb,
		arg.MaxScore,
		arg.Published,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Difficulty,
		&i.Statement,
		&i.Constraints,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.MaxScore,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
