name: labyrithm-worker

services:
  judge-worker:
    image: ghcr.io/nayanthanethsara/algotest/backend:latest
    container_name: labyrithm-judge-worker
    privileged: true
    restart: unless-stopped
    command: ["labyrithm-worker"]
    env_file:
      - ./backend/.env
    volumes:
      - /var/local/lib/labyrithm-work:/var/local/lib/labyrithm-work
    networks:
      - labyrithm-worker-net

  promtail:
    image: grafana/promtail:3.0.0
    container_name: labyrithm-worker-promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./monitoring/promtail/promtail-worker-config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - labyrithm-worker-net

networks:
  labyrithm-worker-net:
    name: labyrithm-worker-net
    driver: bridge
