name: algothon-worker

services:
  judge-worker:
    image: ghcr.io/nayanthanethsara/algotest/backend:latest
    container_name: algothon-judge-worker
    privileged: true
    restart: unless-stopped
    command: ["algothon-worker"]
    env_file:
      - ./backend/.env
    volumes:
      - /var/local/lib/algothon-work:/var/local/lib/algothon-work
    networks:
      - algothon-worker-net

  promtail:
    image: grafana/promtail:3.0.0
    container_name: algothon-worker-promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./monitoring/promtail/promtail-worker-config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - algothon-worker-net

networks:
  algothon-worker-net:
    name: algothon-worker-net
    driver: bridge
