"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Plus, Trash2, Eye, Edit3, Save, Globe } from "lucide-react";
import { Markdown } from "./markdown";
import type { Difficulty, ProblemDetail, ProblemInput, Sample } from "@/types/problem";
import { STARTER_PROBLEM_TEMPLATE } from "@/lib/templates";
import { Button, buttonVariants } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";

type ProblemEditorProps = {
  initialData?: ProblemDetail | null;
  onSave: (input: ProblemInput) => Promise<void>;
  pending: boolean;
};

export function ProblemEditor({ initialData, onSave, pending }: ProblemEditorProps) {
  const isEditing = Boolean(initialData);

  const [slug, setSlug] = useState(initialData?.slug ?? STARTER_PROBLEM_TEMPLATE.slug);
  const [title, setTitle] = useState(initialData?.title ?? STARTER_PROBLEM_TEMPLATE.title);
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(!isEditing);

  const [difficulty, setDifficulty] = useState<Difficulty>(
    (initialData?.difficulty as Difficulty) ?? STARTER_PROBLEM_TEMPLATE.difficulty
  );
  const [maxScore, setMaxScore] = useState(
    initialData?.maxScore ?? STARTER_PROBLEM_TEMPLATE.maxScore
  );
  const [timeLimitMs, setTimeLimitMs] = useState(
    initialData?.timeLimitMs ?? STARTER_PROBLEM_TEMPLATE.timeLimitMs
  );
  const [memoryLimitMb, setMemoryLimitMb] = useState(
    initialData?.memoryLimitMb ?? STARTER_PROBLEM_TEMPLATE.memoryLimitMb
  );
  const [published, setPublished] = useState(
    initialData?.published ?? STARTER_PROBLEM_TEMPLATE.published
  );

  const [statement, setStatement] = useState(
    initialData?.statement ?? STARTER_PROBLEM_TEMPLATE.statement
  );
  const [constraints, setConstraints] = useState(
    initialData?.constraints ?? STARTER_PROBLEM_TEMPLATE.constraints
  );
  const [samples, setSamples] = useState<Sample[]>(
    initialData?.samples ?? STARTER_PROBLEM_TEMPLATE.samples
  );

  const [activeTab, setActiveTab] = useState<"edit" | "preview" | "split">("split");
  const [error, setError] = useState<string | null>(null);

  function handleTitleChange(newTitle: string) {
    setTitle(newTitle);
    if (slugAutoGenerated && !isEditing) {
      const generatedSlug = newTitle
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)+/g, "");
      setSlug(generatedSlug);
    }
  }

  function handleSlugChange(newSlug: string) {
    setSlug(newSlug);
    setSlugAutoGenerated(false);
  }

  function handleAddSample() {
    setSamples((prev) => [
      ...prev,
      { ordinal: prev.length + 1, input: "", output: "", explanation: "" },
    ]);
  }

  function handleRemoveSample(index: number) {
    setSamples((prev) => prev.filter((_, i) => i !== index));
  }

  function handleSampleChange(index: number, field: keyof Sample, value: string) {
    setSamples((prev) => prev.map((s, i) => (i === index ? { ...s, [field]: value } : s)));
  }

  async function handleSaveInternal(shouldPublish?: boolean) {
    setError(null);

    if (!slug.trim() || !title.trim() || !statement.trim()) {
      setError("Slug, Title, and Statement are required.");
      return;
    }

    const finalPublished = shouldPublish !== undefined ? shouldPublish : published;
    setPublished(finalPublished);

    try {
      await onSave({
        slug: slug.trim(),
        title: title.trim(),
        difficulty,
        maxScore: Number(maxScore),
        timeLimitMs: Number(timeLimitMs),
        memoryLimitMb: Number(memoryLimitMb),
        published: finalPublished,
        statement,
        constraints,
        samples: samples.map((s, idx) => ({
          ordinal: idx + 1,
          input: s.input,
          output: s.output,
          explanation: s.explanation || undefined,
        })),
      });
    } catch (err: unknown) {
      if (err instanceof Error) {
        setError(err.message);
      } else {
        setError("Failed to save problem.");
      }
    }
  }

  return (
    <div className="flex min-h-screen flex-col bg-background">
      {/* Sticky Header */}
      <header className="sticky top-0 z-40 flex items-center justify-between border-b bg-card px-6 py-3 shadow-sm">
        <div className="flex items-center gap-4">
          <Link
            href="/"
            className={buttonVariants({
              variant: "ghost",
              size: "sm",
              className: "gap-1.5 text-xs text-muted-foreground",
            })}
          >
            <ArrowLeft className="h-4 w-4" /> Back to Console
          </Link>
          <div className="h-4 w-px bg-border" />
          <div className="flex items-center gap-2">
            <h1 className="text-base font-semibold tracking-tight">
              {title || "Untitled Problem"}
            </h1>
            <Badge variant={published ? "default" : "secondary"} className="text-xs">
              {published ? "Published" : "Draft"}
            </Badge>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <Button
            variant="outline"
            size="sm"
            onClick={() => handleSaveInternal(false)}
            disabled={pending}
            className="gap-1.5 text-xs"
          >
            <Save className="h-3.5 w-3.5" /> Save Draft
          </Button>

          <Button
            size="sm"
            onClick={() => handleSaveInternal(true)}
            disabled={pending}
            className="gap-1.5 text-xs"
          >
            <Globe className="h-3.5 w-3.5" /> {pending ? "Saving..." : "Save & Publish"}
          </Button>
        </div>
      </header>

      {/* Main Workspace Body */}
      <div className="mx-auto flex w-full max-w-7xl flex-1 flex-col gap-6 p-6">
        {error && (
          <p className="rounded-md border border-destructive/40 bg-destructive/10 px-4 py-2.5 text-sm font-medium text-destructive">
            {error}
          </p>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
          {/* Left Panel: Configuration Controls */}
          <Card className="lg:col-span-4 p-5 flex flex-col gap-4 shadow-sm border border-border">
            <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Problem Metadata
            </h2>

            <div className="flex flex-col gap-1">
              <label className="text-xs font-medium text-muted-foreground block">
                Problem Title
              </label>
              <Input
                value={title}
                onChange={(e) => handleTitleChange(e.target.value)}
                placeholder="e.g. Range Sum Queries"
                required
              />
            </div>

            <div className="flex flex-col gap-1">
              <label className="text-xs font-medium text-muted-foreground block">Slug</label>
              <Input
                value={slug}
                onChange={(e) => handleSlugChange(e.target.value)}
                placeholder="e.g. range-sum"
                disabled={isEditing}
                required
                className="font-mono"
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div className="flex flex-col gap-1">
                <label className="text-xs font-medium text-muted-foreground block">
                  Difficulty
                </label>
                <select
                  value={difficulty}
                  onChange={(e) => setDifficulty(e.target.value as Difficulty)}
                  className="h-9 w-full rounded-md border bg-background px-3 text-xs"
                >
                  <option value="Easy">Easy</option>
                  <option value="Medium">Medium</option>
                  <option value="Hard">Hard</option>
                </select>
              </div>

              <div className="flex flex-col gap-1">
                <label className="text-xs font-medium text-muted-foreground block">Max Score</label>
                <Input
                  type="number"
                  value={maxScore}
                  onChange={(e) => setMaxScore(Number(e.target.value))}
                  min={1}
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div className="flex flex-col gap-1">
                <label className="text-xs font-medium text-muted-foreground block">
                  Time Limit (ms)
                </label>
                <Input
                  type="number"
                  value={timeLimitMs}
                  onChange={(e) => setTimeLimitMs(Number(e.target.value))}
                  step={500}
                  min={500}
                />
              </div>

              <div className="flex flex-col gap-1">
                <label className="text-xs font-medium text-muted-foreground block">
                  Memory Limit (MB)
                </label>
                <Input
                  type="number"
                  value={memoryLimitMb}
                  onChange={(e) => setMemoryLimitMb(Number(e.target.value))}
                  step={64}
                  min={64}
                />
              </div>
            </div>

            <div className="pt-2 border-t mt-2">
              <label className="flex items-center gap-2 cursor-pointer text-xs font-medium">
                <input
                  type="checkbox"
                  checked={published}
                  onChange={(e) => setPublished(e.target.checked)}
                  className="rounded border h-4 w-4"
                />
                Published to Contestants
              </label>
            </div>
          </Card>

          {/* Right Panel: Statement & Preview Workspace */}
          <div className="lg:col-span-8 flex flex-col gap-6">
            <Card className="p-5 flex flex-col gap-4 shadow-sm border border-border">
              <div className="flex items-center justify-between">
                <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Statement & Markdown Editor
                </h2>

                <Tabs
                  value={activeTab}
                  onValueChange={(v) => setActiveTab(v as "edit" | "preview" | "split")}
                >
                  <TabsList className="h-8">
                    <TabsTrigger value="edit" className="gap-1 text-xs h-7">
                      <Edit3 className="h-3 w-3" /> Edit
                    </TabsTrigger>
                    <TabsTrigger value="split" className="text-xs h-7">
                      Split View
                    </TabsTrigger>
                    <TabsTrigger value="preview" className="gap-1 text-xs h-7">
                      <Eye className="h-3 w-3" /> Live Preview
                    </TabsTrigger>
                  </TabsList>
                </Tabs>
              </div>

              {activeTab === "edit" && (
                <Textarea
                  value={statement}
                  onChange={(e) => setStatement(e.target.value)}
                  rows={14}
                  placeholder="Write statement in Markdown format..."
                  className="font-mono text-xs leading-relaxed"
                  required
                />
              )}

              {activeTab === "preview" && (
                <div className="min-h-[300px] rounded-md border bg-muted/10 p-5">
                  <Markdown>{statement || "*No statement provided.*"}</Markdown>
                </div>
              )}

              {activeTab === "split" && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <Textarea
                    value={statement}
                    onChange={(e) => setStatement(e.target.value)}
                    rows={14}
                    placeholder="Write statement in Markdown format..."
                    className="font-mono text-xs leading-relaxed"
                    required
                  />
                  <div className="min-h-[300px] max-h-[360px] overflow-y-auto rounded-md border bg-muted/10 p-4">
                    <Markdown>{statement || "*No statement provided.*"}</Markdown>
                  </div>
                </div>
              )}
            </Card>

            {/* Constraints Block */}
            <Card className="p-5 flex flex-col gap-3 shadow-sm border border-border">
              <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                Constraints (Markdown & LaTeX Math)
              </label>
              <Textarea
                value={constraints}
                onChange={(e) => setConstraints(e.target.value)}
                rows={3}
                placeholder="- $1 \le N \le 10^5$"
                className="font-mono text-xs"
              />
            </Card>

            {/* Sample Test Cases */}
            <Card className="p-5 flex flex-col gap-4 shadow-sm border border-border">
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                    Public Sample Test Cases
                  </h2>
                  <p className="text-xs text-muted-foreground">
                    These sample inputs and outputs are visible to contestants.
                  </p>
                </div>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleAddSample}
                  className="h-8 text-xs gap-1"
                >
                  <Plus className="h-3.5 w-3.5" /> Add Sample Case
                </Button>
              </div>

              <div className="flex flex-col gap-4">
                {samples.map((s, idx) => (
                  <div key={idx} className="rounded-lg border p-4 bg-muted/10 relative">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                        Sample #{idx + 1}
                      </span>
                      {samples.length > 1 && (
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => handleRemoveSample(idx)}
                          className="h-7 w-7 text-destructive hover:bg-destructive/10"
                        >
                          <Trash2 className="h-3.5 w-3.5" />
                        </Button>
                      )}
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-3">
                      <div className="flex flex-col gap-1">
                        <label className="text-xs text-muted-foreground block">
                          Standard Input
                        </label>
                        <Textarea
                          value={s.input}
                          onChange={(e) => handleSampleChange(idx, "input", e.target.value)}
                          rows={3}
                          className="font-mono text-xs"
                        />
                      </div>
                      <div className="flex flex-col gap-1">
                        <label className="text-xs text-muted-foreground block">
                          Standard Output
                        </label>
                        <Textarea
                          value={s.output}
                          onChange={(e) => handleSampleChange(idx, "output", e.target.value)}
                          rows={3}
                          className="font-mono text-xs"
                        />
                      </div>
                    </div>

                    <div className="flex flex-col gap-1">
                      <label className="text-xs text-muted-foreground block">
                        Explanation (Optional)
                      </label>
                      <Input
                        value={s.explanation || ""}
                        onChange={(e) => handleSampleChange(idx, "explanation", e.target.value)}
                        placeholder="e.g. 1 + 2 + 3 = 6"
                        className="text-xs"
                      />
                    </div>
                  </div>
                ))}
              </div>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}
