"use client";

import { useState } from "react";
import Link from "next/link";
import {
  AlertCircleIcon,
  ArrowLeftIcon,
  CheckCircle2Icon,
  BookOpenIcon,
  CpuIcon,
  FileTextIcon,
  GlobeIcon,
  RotateCcwIcon,
  SaveIcon,
  XIcon,
} from "lucide-react";
import { toast } from "sonner";
import type {
  Difficulty,
  ProblemDetail,
  ProblemInput,
  Sample,
  TestCaseMetadata,
} from "@/types/problem";
import { STARTER_PROBLEM_TEMPLATE } from "@/lib/templates";
import { getErrorMessage } from "@/lib/errors";
import { Alert, AlertAction, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button, buttonVariants } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Spinner } from "@/components/ui/spinner";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { MIN_EVALUATION_TEST_CASES } from "@/lib/testcase-utils";
import { useProblemDraft } from "./problem-editor/use-problem-draft";
import { ProblemMetadataCard } from "./problem-editor/problem-metadata-card";
import { StatementTab } from "./problem-editor/statement-tab";
import { SamplesTab } from "./problem-editor/samples-tab";
import { TestCasesTab } from "./problem-editor/test-cases-tab";

type ProblemEditorProps = {
  initialData?: ProblemDetail | null;
  initialTests?: TestCaseMetadata[];
  initialTab?: "statement" | "samples" | "tests";
  autoOpenAction?: "add" | "batch";
  onSave: (input: ProblemInput, action?: "add" | "batch") => Promise<void>;
  pending: boolean;
};

export function ProblemEditor({
  initialData,
  initialTests,
  initialTab,
  autoOpenAction,
  onSave,
  pending,
}: ProblemEditorProps) {
  const isEditing = Boolean(initialData);

  const [slug, setSlug] = useState(initialData?.slug ?? STARTER_PROBLEM_TEMPLATE.slug);
  const [title, setTitle] = useState(initialData?.title ?? STARTER_PROBLEM_TEMPLATE.title);
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(!isEditing);

  const [difficulty, setDifficulty] = useState<Difficulty>(
    (initialData?.difficulty as Difficulty) ?? STARTER_PROBLEM_TEMPLATE.difficulty
  );
  const [maxScore, setMaxScore] = useState(
    initialData?.maxScore ?? STARTER_PROBLEM_TEMPLATE.maxScore
  );
  const [timeLimitMs, setTimeLimitMs] = useState(
    initialData?.timeLimitMs ?? STARTER_PROBLEM_TEMPLATE.timeLimitMs
  );
  const [memoryLimitMb, setMemoryLimitMb] = useState(
    initialData?.memoryLimitMb ?? STARTER_PROBLEM_TEMPLATE.memoryLimitMb
  );
  const [published, setPublished] = useState(
    initialData?.published ?? STARTER_PROBLEM_TEMPLATE.published
  );

  const [statement, setStatement] = useState(
    initialData?.statement ?? STARTER_PROBLEM_TEMPLATE.statement
  );
  const [constraints, setConstraints] = useState(
    initialData?.constraints ?? STARTER_PROBLEM_TEMPLATE.constraints
  );
  const [samples, setSamples] = useState<Sample[]>(
    initialData?.samples ?? STARTER_PROBLEM_TEMPLATE.samples
  );

  const [tests, setTests] = useState<TestCaseMetadata[]>(() => initialTests ?? []);
  const [lastInitialTests, setLastInitialTests] = useState(initialTests);

  if (initialTests !== lastInitialTests) {
    setLastInitialTests(initialTests);
    if (initialTests && initialTests.length > 0) {
      setTests(initialTests);
    }
  }

  const [activeWorkspaceTab, setActiveWorkspaceTab] = useState<"statement" | "samples" | "tests">(
    initialTab ?? "statement"
  );

  const [lastInitialTab, setLastInitialTab] = useState(initialTab);
  if (initialTab && initialTab !== lastInitialTab) {
    setLastInitialTab(initialTab);
    setActiveWorkspaceTab(initialTab);
  }
  const [error, setError] = useState<string | null>(null);

  // Draft Recovery Hook (saves metadata without heavy test data)
  const { hasSavedDraft, draftRestored, restoreDraft, discardDraft, clearDraftOnSuccess } =
    useProblemDraft(
      isEditing,
      {
        slug,
        title,
        difficulty,
        maxScore,
        timeLimitMs,
        memoryLimitMb,
        statement,
        constraints,
        samples,
        published,
      },
      (draft) => {
        if (draft.slug) setSlug(draft.slug);
        if (draft.title) setTitle(draft.title);
        if (draft.difficulty) setDifficulty(draft.difficulty);
        if (draft.maxScore) setMaxScore(draft.maxScore);
        if (draft.timeLimitMs) setTimeLimitMs(draft.timeLimitMs);
        if (draft.memoryLimitMb) setMemoryLimitMb(draft.memoryLimitMb);
        if (draft.statement) setStatement(draft.statement);
        if (draft.constraints) setConstraints(draft.constraints);
        if (draft.samples) setSamples(draft.samples);
        if (draft.published !== undefined) setPublished(draft.published);
      }
    );

  function handleTitleChange(newTitle: string) {
    setTitle(newTitle);
    if (slugAutoGenerated && !isEditing) {
      const generatedSlug = newTitle
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)+/g, "");
      setSlug(generatedSlug);
    }
  }

  function handleSlugChange(newSlug: string) {
    setSlug(newSlug);
    setSlugAutoGenerated(false);
  }

  // Sample handlers
  function handleAddSample() {
    setSamples((prev) => [
      ...prev,
      { ordinal: prev.length + 1, input: "", output: "", explanation: "" },
    ]);
  }

  function handleRemoveSample(index: number) {
    setSamples((prev) => prev.filter((_, i) => i !== index));
  }

  function handleSampleChange(index: number, field: keyof Sample, value: string) {
    setSamples((prev) => prev.map((s, i) => (i === index ? { ...s, [field]: value } : s)));
  }

  async function handleSaveInternal(shouldPublish?: boolean, action?: "add" | "batch") {
    setError(null);

    if (!slug.trim() || !title.trim()) {
      toast.error("A slug and a title are required.");
      return;
    }

    if (!statement.trim()) {
      toast.error("The problem statement is required.");
      setActiveWorkspaceTab("statement");
      return;
    }

    const finalPublished = shouldPublish !== undefined ? shouldPublish : published;

    if (finalPublished && tests.length < MIN_EVALUATION_TEST_CASES) {
      toast.warning("Not enough evaluation test cases", {
        description: `Publishing requires at least ${MIN_EVALUATION_TEST_CASES} tests — ${tests.length} added so far.`,
      });
      setActiveWorkspaceTab("tests");
      return;
    }

    setPublished(finalPublished);

    try {
      await onSave(
        {
          slug: slug.trim(),
          title: title.trim(),
          difficulty,
          maxScore: Number(maxScore),
          timeLimitMs: Number(timeLimitMs),
          memoryLimitMb: Number(memoryLimitMb),
          published: finalPublished,
          statement,
          constraints,
          samples: samples.map((s, idx) => ({
            ordinal: idx + 1,
            input: s.input,
            output: s.output,
            explanation: s.explanation || undefined,
          })),
        },
        action
      );
      clearDraftOnSuccess();
      toast.success(finalPublished ? "Problem saved and published" : "Draft saved");
    } catch (err) {
      setError(getErrorMessage(err, "Failed to save the problem."));
    }
  }

  return (
    <div className="flex flex-1 flex-col">
      <header className="sticky top-(--app-header-height) z-30 flex flex-col gap-2.5 border-b bg-card/95 px-4 py-2.5 backdrop-blur-xl sm:flex-row sm:items-center sm:justify-between sm:px-6">
        <div className="flex min-w-0 flex-wrap items-center gap-2 sm:gap-3">
          <Link
            href="/problems"
            className={buttonVariants({
              variant: "ghost",
              size: "sm",
              className: "shrink-0 gap-1.5 text-muted-foreground",
            })}
          >
            <ArrowLeftIcon />
            <span className="hidden sm:inline">Back to problems</span>
          </Link>

          <div className="hidden h-4 w-px bg-border sm:block" />

          <div className="flex min-w-0 flex-wrap items-center gap-1.5 sm:gap-2">
            <h1
              className="max-w-40 truncate text-sm font-semibold tracking-tight sm:max-w-65 sm:text-base"
              title={title || "Untitled problem"}
            >
              {title || "Untitled problem"}
            </h1>
            <Badge variant={published ? "default" : "secondary"} className="text-[10px]">
              {published ? "Published" : "Draft"}
            </Badge>
            <Badge
              variant={tests.length >= MIN_EVALUATION_TEST_CASES ? "default" : "destructive"}
              className="font-mono text-[10px]"
            >
              {tests.length}/{MIN_EVALUATION_TEST_CASES} tests
            </Badge>
          </div>
        </div>

        <div className="flex shrink-0 items-center justify-end gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => handleSaveInternal(false)}
            disabled={pending}
            className="gap-1.5"
          >
            {pending ? <Spinner /> : <SaveIcon />} Save draft
          </Button>

          <Button
            size="sm"
            onClick={() => handleSaveInternal(true)}
            disabled={pending}
            className="gap-1.5"
          >
            {pending ? <Spinner /> : <GlobeIcon />} {pending ? "Saving…" : "Save & publish"}
          </Button>
        </div>
      </header>

      {/* Main Workspace Body */}
      <div className="mx-auto flex w-full max-w-7xl flex-1 flex-col gap-4 p-4 sm:p-6">
        {hasSavedDraft && (
          <Alert>
            <RotateCcwIcon />
            <AlertTitle>Unsaved draft recovered</AlertTitle>
            <AlertDescription className="flex flex-col items-start gap-2">
              <span>
                A problem draft from your previous session is still stored in this browser.
              </span>
              <span className="flex gap-1.5">
                <Button size="xs" onClick={restoreDraft}>
                  Restore
                </Button>
                <Button size="xs" variant="ghost" onClick={discardDraft}>
                  Discard
                </Button>
              </span>
            </AlertDescription>
          </Alert>
        )}

        {draftRestored && (
          <Alert className="border-success/30 bg-success/10 text-success">
            <CheckCircle2Icon />
            <AlertDescription className="text-success">Draft restored.</AlertDescription>
          </Alert>
        )}

        {error && (
          <Alert variant="destructive">
            <AlertCircleIcon />
            <AlertTitle>Unable to save this problem</AlertTitle>
            <AlertDescription className="font-mono text-[11px] break-words">
              {error}
            </AlertDescription>
            <AlertAction>
              <Button
                size="icon-xs"
                variant="ghost"
                onClick={() => setError(null)}
                aria-label="Dismiss error"
              >
                <XIcon />
              </Button>
            </AlertAction>
          </Alert>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
          {/* Left Panel: Problem Configuration */}
          <div className="lg:col-span-4">
            <ProblemMetadataCard
              slug={slug}
              title={title}
              difficulty={difficulty}
              maxScore={maxScore}
              timeLimitMs={timeLimitMs}
              memoryLimitMb={memoryLimitMb}
              published={published}
              isEditing={isEditing}
              testsCount={tests.length}
              onTitleChange={handleTitleChange}
              onSlugChange={handleSlugChange}
              onDifficultyChange={setDifficulty}
              onMaxScoreChange={setMaxScore}
              onTimeLimitChange={setTimeLimitMs}
              onMemoryLimitChange={setMemoryLimitMb}
              onPublishedChange={setPublished}
            />
          </div>

          {/* Right Panel: Workspace Tabs */}
          <div className="lg:col-span-8 flex flex-col gap-4">
            <Tabs
              value={activeWorkspaceTab}
              onValueChange={(v) => setActiveWorkspaceTab(v as "statement" | "samples" | "tests")}
              className="w-full"
            >
              <TabsList className="h-10 w-full grid grid-cols-3 bg-muted/40 p-1">
                <TabsTrigger
                  value="statement"
                  className="text-xs gap-1 sm:gap-1.5 h-8 px-1 sm:px-3"
                >
                  <FileTextIcon className="size-3.5 shrink-0" />
                  <span className="hidden sm:inline">Statement & Constraints</span>
                  <span className="sm:hidden">Statement</span>
                </TabsTrigger>

                <TabsTrigger value="samples" className="text-xs gap-1 sm:gap-1.5 h-8 px-1 sm:px-3">
                  <BookOpenIcon className="size-3.5 shrink-0" />
                  <span className="hidden sm:inline">Public Samples</span>
                  <span className="sm:hidden">Samples</span>
                  <Badge
                    variant="outline"
                    className="text-[10px] ml-0.5 sm:ml-1 px-1 sm:px-1.5 py-0"
                  >
                    {samples.length}
                  </Badge>
                </TabsTrigger>

                <TabsTrigger value="tests" className="text-xs gap-1 sm:gap-1.5 h-8 px-1 sm:px-3">
                  <CpuIcon className="size-3.5 shrink-0" />
                  <span className="hidden sm:inline">Judging Test Cases</span>
                  <span className="sm:hidden">Tests</span>
                  <Badge
                    variant={tests.length >= MIN_EVALUATION_TEST_CASES ? "default" : "destructive"}
                    className="text-[10px] ml-0.5 sm:ml-1 px-1 sm:px-1.5 py-0"
                  >
                    {tests.length}/{MIN_EVALUATION_TEST_CASES}
                  </Badge>
                </TabsTrigger>
              </TabsList>

              {/* TAB 1: Statement & Constraints */}
              <TabsContent value="statement" className="mt-4">
                <StatementTab
                  statement={statement}
                  constraints={constraints}
                  onStatementChange={setStatement}
                  onConstraintsChange={setConstraints}
                />
              </TabsContent>

              {/* TAB 2: Public Samples */}
              <TabsContent value="samples" className="mt-4">
                <SamplesTab
                  samples={samples}
                  onAddSample={handleAddSample}
                  onRemoveSample={handleRemoveSample}
                  onSampleChange={handleSampleChange}
                />
              </TabsContent>

              {/* TAB 3: Judging Test Cases */}
              <TabsContent value="tests" className="mt-4">
                <TestCasesTab
                  problemId={initialData?.id}
                  problemSlug={slug}
                  tests={tests}
                  maxScore={Number(maxScore) || 100}
                  onTestsUpdated={setTests}
                  onSaveDraftFirst={(action) => handleSaveInternal(false, action)}
                  autoOpenAction={autoOpenAction}
                />
              </TabsContent>
            </Tabs>
          </div>
        </div>
      </div>
    </div>
  );
}
